var sticker={tWidth:$('#trackInfo').width(),tHeight:'25px',tcolour:null,moStop:true,tSpeed:3,content:null,cps:this.tSpeed,aw:null,mq:null,fsz:parseInt(this.tHeight)-4,lefttime:null,startticker:function(){this.cps=this.tSpeed;var tick='<div style="position:relative;margin:0px;"';if(this.moStop)tick+=' onmouseover="sticker.cps=0" onmouseout="sticker.cps=sticker.tSpeed"';tick+='><div id="mq" style="position:absolute;left:0px;top:0px;"><\/div><\/div>';$('#trackInfo').html(tick);this.mq=document.getElementById("mq");this.mq.style.left=(parseInt(this.tWidth)+10)+"px";this.mq.innerHTML='<span id="tx">'+this.content+'<\/span>';this.aw=document.getElementById("tx").offsetWidth;this.lefttime=setInterval("sticker.scrollticker()",50);},stopticker:function(){try{if(this.lefttime!='null'){window.clearInterval(this.lefttime);}}catch(e){}},scrollticker:function(){this.mq.style.left=(parseInt(this.mq.style.left)>(-10-this.aw))?parseInt(this.mq.style.left)-this.cps+"px":parseInt(this.tWidth)+10+"px";}}
var Layout={};Layout.highlightRow=function(arg){try{Layout.resetSelectedRow();var songId=gaanaMaster.getCurrentInfo().id;Layout.playSong();_activeSongID=songId;playerQueue.updateCurrent(_activeSongID);Layout.rendereRcommendation(songId);}catch(e){}}
Layout.playSong=function(){if(gaanaMaster.getCurrentInfo()==null)return;var songId=gaanaMaster.getCurrentInfo().id;var songInfo=gaanaMaster.getCurrentInfo()
if(songId>0){var atitle=(typeof songInfo['atitle']!='undefined')?songInfo['atitle']:songInfo['albumtitle'];document.title=gaanaMaster.getCurrentInfo()['title']+"-"+atitle}
$('.play_pause').removeClass('pause-icon');$('.rt_arw').removeClass('pause-icon');$('.playicon'+songId).addClass('pause-icon');$('.play-song-queue').removeClass('pause-song-queue');$('#qsong'+songId).addClass('pause-song-queue');isPlayingStatus=true;}
Layout.pauseSong=function(arg){if(gaanaMaster.getCurrentInfo()==null)return;var songId=gaanaMaster.getCurrentInfo().id;$('.play_pause').removeClass('pause-icon');$('.rt_arw').removeClass('pause-icon');$('.play-song-queue').removeClass('pause-song-queue');isPlayingStatus=false;}
Layout.resetSelectedRow=function(){$(".playingNow").removeClass("playingNow");}
Layout.recTimer=null;Layout.cache={};Layout.enableRecommendation=false;Layout.adjustRecommendationHeight=function(){if(Layout.enableRecommendation==false){$(".weRecommend").hide();$("#falshplayerouter").css({height:"84px"});}else{$(".weRecommend").show();$("#falshplayerouter").css({height:"104px"});}}
Layout.getRecommedationData=function(songId,cb,type,title){$('.hd_img').addClass('_loader')
$('.bottom-popup').animate({bottom:'80px'},{duration:300});$('.notification_msg').html('Starting your radio');gAnalyticChannelClick('Echonest Song Radio','Play',title);if(Layout.cache[songId+"_"]){if(cb){cb(Layout.cache[songId+"_"]);}}else{$.ajax({type:'post',url:TMUrl+'ajax/xmldata',data:{"action":'relatedtrackdetail',"id":songId,"datatype":'jsonobj'},success:function(data){Layout.cache[songId+"_"]=data;if(cb){cb(data);$('.bottom-popup').animate({bottom:'-60px'},150);$('.hd_img').removeClass('_loader');for(sources in _variables['source']){delete _variables['source'][sources];}}},error:function(XMLHttpRequest,textStatus,errorThrown){try{}catch(e){}}});}}
Layout.getRecommendation=function(songId,cb){Layout.adjustRecommendationHeight();if(Layout.enableRecommendation==true){Layout.getRecommedationData(songId,cb);}}
Layout.showHideRcommendation=function(is){var fn=(is==true)?"show":"hide";$("#werecommendation")[fn]();}
Layout.showHideGaanaRadio=function(is){var fn=(is==true)?"show":"hide";$(".mainPlayer .rgtSeprator")[fn]();}
Layout.showHideGaanaIcon=function(is){var fn=(is==true)?"show":"hide";$(".mainPlayer .radio")[fn]();}
Layout.enableGaanaIcon=function(is){$(".mainPlayer #radio").unbind('click');if(!is){$(".mainPlayer #radio").unbind('click');}else{$("#radio").bind("click",function(){gaanaMaster.surprisePlay();})}}
Layout.fav=function(row){$('#'+row.id).parent().data('row').action=row.action
if($('.spritePlayer.fav').attr('data-value')!=null){try{if($('.spritePlayer.fav').data('row').id==row.id){$('.spritePlayer.fav').data('row').action=row.action;$('.spritePlayer.fav').removeClass('Active').addClass((row['action']==0)?'':'Active')}}catch(e){alert(e.message)}}}
Layout.buildAlbumHtml=function(row,returnUrl){if(typeof row.albumseokey=='undefined')return[];return['<a href="/album/',row.albumseokey,'" class="albumNamePl white pjax">',row.albumtitle,'</a>'];};Layout.nowPlayingbuildAlbumHtml=function(row,returnUrl){if(typeof row.album=='undefined')return[];var albumarr=row.album.split('_')
var albumId=albumarr.slice(-1)[0]
var albumName=albumarr.slice(0,-1).join(' ')
var albumUrl=utility.getUrl(albumName,albumId,row.albumseokey);if(typeof returnUrl!='undefined'&&returnUrl==true){return albumUrl;}else{return['<a href="#!/albums/',albumUrl,'" class="albumNamePl NPalbumName">',albumName,'</a>'];}};Layout.buildArtistHtml=function(row){try{if(typeof row.artist=='undefined')return[];var artists=(row.artist!=null)?row.artist.split(","):'no';var artistobj=new Array();for(i=0;i<artists.length;i++){var arname_id=artists[i].split("###");var name=(typeof $.trim(arname_id[0])!='undefined'&&$.trim(arname_id[0])!='')?$.trim(arname_id[0]):'';var id=(typeof arname_id[1]!='undefined'&&arname_id[1]!='')?arname_id[1]:'';var seokey=(typeof arname_id[2]!='undefined'&&arname_id[2]!='')?arname_id[2]:'';if(typeof seokey!='undefined'&&seokey!=null&&seokey!=''){if(seokey.length>0){Url='/artist/'+seokey}}else{Url='/artist/'+encodeURIComponent(name).replace(' ','_')+"_"+id;}
var artisHtml=['<a class="pjax albumNamePl white" href="',Url,'">',name,'</a>'].join('');artistobj.push(artisHtml);artisHtml=null;}
return artistobj;}
catch(e){}}
Layout.resetCurrentSongInfo=function(){$('#trackThumb').html("");}
Layout.renderCurrentSongInfo=function(data,index){try{var songInfo=data;$('#trackInfo').show();index=(typeof(index)!='undefined')?index:0;try{var html=[songInfo['title'],'<span> - ',Layout.buildAlbumHtml(songInfo).join(''),'</span>'].join('')
$('#trackInfo').html(html);var atitle=(typeof songInfo['atitle']!='undefined')?songInfo['atitle']:songInfo['albumtitle'];$('.thumbHolder').html(['<img src="',songInfo['albumartwork'],'" width="60" height="60" />'].join(''));if(typeof songInfo['albumseokey']!='undefined'&&songInfo['albumseokey']!=''&&songInfo['albumseokey']==null){$('.thumbHolder').attr('href','/album/'+songInfo['albumseokey'])
$('.thumbHolder').attr('class','thumbHolder pjax')}else{$('.thumbHolder').attr('href','javascript:void(0)')
$('.thumbHolder').attr('class','thumbHolder')}
$('#mainPlayer #favorite').removeClass('unfavorite')
if($('#parent-row-song'+songInfo['id']).length>0){var row=$.parseJSON($('#parent-row-song'+songInfo['id']).html())
if(row['status']==1){$('#mainPlayer #favorite').addClass('unfavorite');$('#mainPlayer #favorite').attr('title','Remove from favorite')}else if(row['status']==0){$('#mainPlayer #favorite').attr('title','Add to favorites')}}else if(songInfo['status']==1){$('#mainPlayer #favorite').addClass('unfavorite')}else if(songInfo['status']==0){$('#mainPlayer #favorite').attr('title','Add to favorites')}}catch(e){alert(e.message)}
songInfo=null;$(".queEmpty").hide();}catch(e){utility.errorLog(e.message,'Layout.renderCurrentSongInfo');}}
Layout.renderNextSongInfo=function(nextSongInfo){$('#nextSongInfoId').html(['<h3><span class="nextSongChild" style="display:none"><a class="songName" href="javascript:void(0)">',nextSongInfo.title,'</a> - ',Layout.buildAlbumHtml(nextSongInfo).join(''),' - ',Layout.buildArtistHtml(nextSongInfo).join(','),'</span></h3>'].join(''))
$(".nextSongInfo .songName").unbind('click');$(".nextSongInfo .songName").bind('click',function(){if(gaanaMaster){gaanaMaster.playNext();}});$(".nextSongChild").show();}
Layout.resetNextSongInfo=function(){$(".nextSongInfo .songName").unbind('click');$('#nextSongInfoId').html("");}
Layout.showHideNextSongInfo=function(is){var fn=(is==true)?"show":"hide";$(".nextSongInfo")[fn]();}
Layout.showHideSocial=function(is){var fn=(is==true)?"show":"hide";$(".mainPlayer .social")[fn]();$(".mainPlayer .songadded")[fn]();}
Layout.showHideSongQueue=function(is){var fn=(is==true)?"show":"hide";$(".mainPlayer .songadded")[fn]();}
Layout.renderArtistPreInfo=function(info){if(typeof info!='undefined'&&info!=null){var isPreroll=(typeof info.preroll!='undefined'&&info.preroll!='')?info.preroll:false;if(isPreroll)
_targetStr=" target='_blank'";$('#nextSongInfoId').html('')
$('#trackInfo').html('<span class="songName">'+info.title+'</span>');if(typeof info.playerartwork!='undefined'&&info.playerartwork!=''){$('.thumbHolder').html(['<a href="',info['impression_tracking_url'],'" ',_targetStr,'><img src="',info['playerartwork'],'" width="60" height="60" /><a>'].join(''));}
$(".nextSongChild").hide();}}
Layout.renderSogPreInfo=function(info){if(typeof info!='undefined'&&info!=null){$('#nextSongInfoId').html('')
$('#trackInfo').html('<span class="songName">'+info.zoomArtistName+'</span>');$(".nextSongChild").hide();}}
Layout.updateCataLog=function(lastid,feedbacktype){trace('sendfeedbacktoechonest')
$.ajax({url:"/ajax/echonestfeedback",data:{"id":lastid,'feedbacktype':feedbacktype},type:'post',success:function(data){}});}
var Ads={};Ads.ids={"adPlayerRight":"adPlayerRight","adPlayer_468x60":"adPlayer_468x60",'iframeiddiv':'iframeiddiv','centerZone':'gaanaads'};Ads.getHolder=function(id){return this.ids[id]||null;};Ads.showAd=function(adId,stay,arg){var h=this.getHolder(adId);var songInfo=$.parseJSON(arg.songInfo);switch(adId){case"adPlayerRight":$(".adPlayer").css({right:"-1000px"});$(".mainPlayer").animate({width:"75%"},1000);$("#"+h).animate({right:"7"},1000);break;case"adPlayer_468x60":$("#"+h).animate({bottom:"95px"},1000);break;case"iframeiddiv":getAirtelAd(songInfo.id,songInfo.title,songInfo.albumid,songInfo.albumname,123)
break;case"fantaModal":try{var title=songInfo.title.split(" ")
title=title[0];var url="http://gaana.com/share/";var id=songInfo.id
url=url+'t'+title+'I'+id;FB.ui({link:url,picture:'http://static.gaana.com//images/channel/35//crop_110x110_35.jpg',method:'send',message:'Dedicate this song to .'},function(response)
{})}catch(e){alert(e.message)
utility.errorLog(e.message,'Fanta');}
break;case"centerZone":try{renderMirindaAd(arg.addinfo);}catch(e){alert(e.message)}
break;case"airtelAds":try{songInfo=gaanaMaster.getCurrentInfo();var _div="";_div='<div class="left-p"><img src="../images/strip_above_player_left.jpg" alt="promo"/></div><div class="right-p"><img src="../images/strip_above_player_right.jpg" alt="promo"/></div>';$("#strip_above_player").addClass("strip_above_player").html(_div).animate({bottom:'60px'},{duration:500});}catch(e){alert(e.message)}
return;case"formulaOne":try{songInfo=gaanaMaster.getCurrentInfo();var _div="";_div='<div class="strip_above_player_formulaone" style="bottom: 60px; width:100%"><div class="left-p"><img alt="promo" src="'+TMUrl+'/images/formulaOne/left_z.jpg"></div><div class="center-p"><a href="http://pubads.g.doubleclick.net/gampad/clk?id=64519059&iu=/7176/IndiatimesTracker/Parx_F1Strip_Gaana_22OCT" target="_blank"><img alt="promo" src="'+TMUrl+'/images/formulaOne/right_p.jpg"></a></div><div class="right-p"><a href="http://www.zigwheels.com/motorsports/formula1" target="_blank"><img alt="promo" src="'+TMUrl+'/images/formulaOne/right_zigwheel.jpg"></a></div></div>';$("#strip_above_player").addClass("strip_above_player_formula_one").html(_div).animate({bottom:'60px'},{duration:500});}catch(e){alert(e.message)}
break;default:$("#"+h).fadeIn("fast");break;}
var timeout=(stay||10000);if(timeout>0){timeoutid=setTimeout(function(){Ads.hideAd(adId);},timeout);document.getElementById(h).timeoutid=timeoutid}};Ads.hideAd=function(adId){var h=this.getHolder(adId);if(h){switch(adId){case"adPlayerRight":$(".mainPlayer").animate({width:"100%"},1000);$("#"+h).animate({right:"-1000px"},1000);break;case"adPlayer_468x60":$("#"+h).animate({bottom:"-175px"},1000);break;case"iframeiddiv":break;default:$("#"+h).fadeOut("fast");break;}
clearTimeout(document.getElementById(h).timeoutid);}}
var Logs={url:TMUrl+"ajax/log",track_id:null,radioTimer:0,addTrackLog:function(){try{var _uiCtrlr=gaanaMaster.getUIController();var _snd=jsPlayer.getSound("msPlayer");var play_song_source_array=["Unknown","Others","Album","Playlist","Artist","Radio Mirchi","Channel","Third Party App","Preroll","RadioGaana","Own Favourite Songs","Own Playlist"];if(typeof _playedtime!='undefined'&&_playedtime!="00:00"){var last_track_id=(typeof _currentSogId!='undefined'&&_currentSogId!='')?_currentSogId:0;var params={"track_id":_currentSogId,"source":_source,"source_id":_source_id,'duration':_playedtime,'platform':'web'};gAnalyticChannelClick(play_song_source_array[_source],'Play',_currentSogId);_snd.trackLog(params)}else{var params={"track_id":_currentSogId,"source":_source,"source_id":_source_id,'platform':'web'};gAnalyticChannelClick(play_song_source_array[_source],'Play',_currentSogId);_snd.trackLog(params)}}catch(e){}},update:function(track_id,timePlayed){var params={'time_played':timePlayed,'last_track_id':track_id}
this.add(params);},startRadioLog:function(cb){function insertRadioLog(cb){var _snd=jsPlayer.getSound("msPlayer");var stationId=superCookie.getItem("stationid");var params={};params.type="radio";params.track_id=stationId;params.station_id=stationId;params.time_played=uiController.getTime().time||"00:00";params.duration=uiController.getTime().time||"00:00";_playedtime=uiController.getTime().time||"00:00";params.last_track_id="0";params.tot_time_played="0";_snd.trackLog(params)
return;$.ajax({type:'post',url:Logs.url,data:params,dataType:'json',success:function(data){if(cb){cb(data);}},error:function(XMLHttpRequest,textStatus,errorThrown){try{}catch(e){}}});}
this.stopRadioLog();this.radioTimer=setInterval(insertRadioLog,180*1000);},stopRadioLog:function(){if(this.radioTimer){clearInterval(this.radioTimer);}},addRadioLogWithTrack:function(param){var _snd=jsPlayer.getSound("msPlayer");_currentSogId=(param&&param.id)?param.id:0;_source=5
_source_id=superCookie.getItem("stationid");_playedtime=uiController.getTime().time||"00:00";Logs.addTrackLog();}}