declare @ToDeleteSrNo table
(
DishPaymentSrNo bigint

)
insert into @ToDeleteSrNo
select DishPaymentSrNo from tbl_ReconMaster
where  RecordTypeId in ('E' )
and UserId = 'AutoGenerated'
group by DishPaymentSrNo,WONumber having COUNT(DishPaymentSrNo) > 1 and DishPaymentSrNo <> 0 

declare @ToDeleteWO table
(
WONumber varchar(20)
)
insert into @ToDeleteWO
select 
distinct r.WONumber
from 
@ToDeleteSrNo td
inner join tbl_ReconMaster r on td.DishPaymentSrNo = r.DishPaymentSrNo


select * from @ToDeleteWO
declare @WO varchar(20)
while(exists(select * from @ToDeleteWO))
begin
	set @WO = (select top 1 wonumber from @ToDeleteWO)
	delete from tbl_ReconMaster where WONumber = @WO and RecordTypeId = 'E' and UserId = 'AutoGenerated'
	exec usp_insAutomatedReconMasterRecordsForServiceCalls @Wo
	delete from @ToDeleteWO where WONumber = @WO
end






