declare @WONumber varchar(20) = '1000031584113016'
select * from tbl_ReconMaster where WONumber = @WONumber and RecordTypeId = 'E'

select
@WoNumber , 'R0101' , dp.TaskType , tp.TaskNumber , dp.PaymentAmount , dp.PaymentAmount , GETDATE() , 'Autogenerated' , dp.TaskDescription , tp.ServiceCode , GETDATE() , tp.Description , tp.TaskNumber , dp.SrNo , ''
from 
tbl_Data_Job_Setup tjs 
inner join tbl_DishPayment dp on tjs.WONumber = dp.WONumber
inner join tbl_ServiceCodeToTaskPayment tp on dp.TaskDescription = tp.Description

where
tjs.WONumber = @WoNumber
and
tjs.WorkorderType = 'NC'
and
tp.ServiceCode = 'P2'
and 
tjs.ServiceCodes like '%' + tp.ServiceCode + '%' 
and dp.PaymentAmount = 125 and dp.TaskType = 'L'


select
@WoNumber , 'R0101' , dp.TaskType , '174' , dp.PaymentAmount , dp.PaymentAmount , GETDATE() , 'Autogenerated' , dp.TaskDescription , rsc.ServiceCode , GETDATE() , rsc.Description , rsc.StockNo, dp.SrNo , ''
from 
tbl_Data_Job_Setup tjs 
inner join tbl_DishPayment dp on tjs.WONumber = dp.WONumber
inner join tbl_Wo2InvTxn wt on tjs.WONumber = wt.WoNumber
inner join tbl_InvTxnLine tl on wt.InvTxnId = tl.InvTxnId
inner join tbl_InvTxnOut2InUnit o2iu on o2iu.InvTxnLineOutId = tl.InvTxnLineId
inner join tbl_InvTxnUnit u on o2iu.InvTxnUnitId = u.InvTxnUnitId

inner join tbl_ReconServiceCodeGrid rsc on rsc.StockNo = tl.ProductId
where
tjs.WONumber = @WoNumber
and 
u.SerialNo2 = dp.TaskDescription
and rsc.EquipmentReimAmount = dp.PaymentAmount 
and dp.TaskType = 'E' and tjs.ServiceCodes like '%' +rsc.ServiceCode+'%'

select
@WoNumber , 'R0101' , dp.TaskType , rsc.ServiceCode , dp.PaymentAmount , dp.PaymentAmount , GETDATE() , 'Autogenerated' , dp.TaskDescription , rsc.ServiceCode , GETDATE() , rsc.Description , rsc.StockNo, dp.SrNo , ''
from 
tbl_Data_Job_Setup tjs 
inner join tbl_DishPayment dp on tjs.WONumber = dp.WONumber
inner join tbl_ReconServiceCodeGrid rsc on rsc.Description = dp.TaskDescription
inner join tbl_Wo2InvTxn wt on tjs.WONumber = wt.WoNumber
inner join tbl_InvTxnLine tl on wt.InvTxnId = tl.InvTxnId
where
tjs.WONumber = @WoNumber
and rsc.EquipmentReimAmount = dp.PaymentAmount 
and dp.TaskType = 'E'  and tjs.ServiceCodes like '%' +rsc.ServiceCode+'%'

 and tl.ProductId = rsc.StockNo
 
 select
distinct @WoNumber , 'R0101' , dp.TaskType , rsc.ServiceCode , dp.PaymentAmount , dp.PaymentAmount , GETDATE() , 'Autogenerated' , dp.TaskDescription , rsc.ServiceCode , GETDATE() , rsc.Description , '', dp.SrNo , ''
from 
tbl_Data_Job_Setup tjs 
inner join tbl_DishPayment dp on tjs.WONumber = dp.WONumber
inner join tbl_ReconServiceCodeGrid rsc on rsc.Description = dp.TaskDescription

where
tjs.WONumber = @WoNumber
and rsc.EquipmentReimAmount = dp.PaymentAmount 
and dp.TaskType = 'E' and tjs.ServiceCodes like '%' +rsc.ServiceCode+'%'  

select
distinct @WoNumber , 'R0101' , dp.TaskType , rsc.ServiceCode , dp.PaymentAmount , dp.PaymentAmount , GETDATE() , 'Autogenerated' , dp.TaskDescription , rsc.ServiceCode , GETDATE() , rsc.Description , '', dp.SrNo , ''
from 
tbl_Data_Job_Setup tjs 
inner join tbl_DishPayment dp on tjs.WONumber = dp.WONumber

inner join tbl_ReconServiceCodeGrid rsc on rsc.Description = dp.TaskDescription
where
tjs.WONumber = @WoNumber
and rsc.EquipmentReimAmount = dp.PaymentAmount 
and dp.TaskType = 'E' and dp.TaskDescription like '%connectivity%'



